### PR TITLE
Wizard: Update text for name validation

### PR DESCRIPTION
**Pull request by regexowl**
This updates helper text for blueprint name validation, making the "word characters" more specific.

### CODE REVIEW

**Review by ondrejbudai — APPROVED** [review]
I think this is easier to understand, thanks! :)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
Yeah, definitely better :+1:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
