### PR TITLE
WizardV2: Filesystem draggable mount point

### PR DESCRIPTION
**Pull request by amirfefer**
This PR adds support for re-ordering mount points in file system step by adding `draggable` support for the table.

https://github.com/osbuild/image-builder-frontend/assets/11807069/7ecda742-6288-42db-ab7e-489db4f1e3b2

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Thanks @amirfefer :+1: Works well and code looks similar to what we had in the v1 wizard :orange_heart: 

Do you think it makes sense to add any tests here?

**Comment by ezr-ondrej** [comment]
@regexowl @mgold1234 WDYT about this one? It might be good to get this one in first and only then #1905 :)

**Comment by mgold1234** [comment]
yes it may be good to merge this first, I am reviewing it now @ezr-ondrej

**Comment by amirfefer** [comment]
Testing drag and drop with jsdom is not trivial, jsdom has it own benefits, but  it still an abstraction of a real browser.
React testing library official `drag` event doesn't work with jsdom - https://testing-library.com/docs/example-drag/

**Review by regexowl — APPROVED** [review]
Looks good and works great, thanks a lot @amirfefer!

Even though it would be nice to have a unit test for this in the future, testing draggability in jsdom is not easy (which I guess was the reason why the functionality didn't have any tests in V1 either :sweat_smile:). So let's not block on that

**Comment by ezr-ondrej** [comment]
> Testing drag and drop with jsdom is not trivial

Thanks for looking into it :orange_heart:

**Pull request merged**
