### PR TITLE
Blueprint: enable import/export in ephemeral

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Adds ability to enable a feature flag in Ephemeral environment by default.

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by avitova — APPROVED** [review]
LGTM

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
I've self merged, it's simple feature, it has an ack, let me know if you find issues, I'll fix it immediately

**Pull request merged**
