### PR TITLE
test: Clean up FSC tests

### PR DESCRIPTION
**Pull request by regexowl**
This cleans up FSC test file a bit after tests were moved here from `CreateImageWizard.test.tsx`.

### CODE REVIEW

**Review by mgold1234 — DISMISSED** [review]
/lgtm

**Comment by mgold1234** [comment]
can you look into the failure tests please?
Screenshot 2024-08-14 at 11 24 19

**Review by ezr-ondrej — DISMISSED** [review]

**Comment by regexowl** [comment]
Rebased and ready for re-review :nerd_face:

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
