### PR TITLE
src: add package step to wizard

### PR DESCRIPTION
**Pull request by jkozol**
The additional package selection step is added to the create image wizard. This step currently uses mock data set in packages.json. There are still a few things needed. Empty and loading state text needs to be added, actual data and routing needs to be supported, pagination needs to actual page through the data list. Tests need to be added.

selectPackagesV0

### CODE REVIEW

**Comment by andreasn** [comment]
Are you planning on changing this to a dual list selector, as in Katie's latest wireframes (v4)?
https://www.patternfly.org/v4/components/dual-list-selector

**Comment by jkozol** [comment]
@katierik this is my draft PR for package selection.

**Comment by katierik** [comment]
Based on the discussion earlier & design changes I'll wait to review :)

**Comment by jkozol** [comment]
So the design changes may be painful to implement. There is no current way to do it using Patternfly's react components. There may be a way using the html but it will be time intensive. I created a request for enhancement [here](https://github.com/patternfly/patternfly-react/issues/5436). I am working on other features for now.

**Comment by jkozol** [comment]
@Gundersanne I just realized that we need the package `summary` not the `description`. I did not realize until now but the summary is much shorter than the description. 

**This is with the description:**
description


**This is with the summary:**
summary

**Comment by Gundersanne** [comment]
ah I'll change that asap :)

**Comment by jkozol** [comment]
Closed in favor of #86

**Pull request closed without merging**
