### PR TITLE
test: Move mocks to setup file

### PR DESCRIPTION
**Pull request by regexowl**
This moves all the mocks used throughout our test files into the test setup file.

### CODE REVIEW

**Review by ezr-ondrej — COMMENTED** [review]
Love it, I hate setups in all the files, but one question:

What do I do if I need my test to disable flag?
I'm generally behind the idea of enabling all by default, maybe even defaulting to true for all. But there might be cases I want flag disabled :thinking:

**Comment by regexowl** [comment]
> Love it, I hate setups in all the files, but one question:
> 
> What do I do if I need my test to disable flag? I'm generally behind the idea of enabling all by default, maybe even defaulting to true for all. But there might be cases I want flag disabled 🤔

Great question! AFAIK you can unmock in the context of any test and re-mock with values you'd like to use. Took one of the smaller files - for example in `test/edge/EdgeImagesTable.test.tsx` you could do something like:
```typescript
    vi.unmock('@unleash/proxy-client-react');
    vi.mock('@unleash/proxy-client-react', () => ({
      useUnleashContext: () => vi.fn(),
      useFlag: vi.fn((flag) =>
        flag === 'image-builder.firstboot.enabled' ? true : false
      ),
    }));
```

and the test should start failing as it's switching the boolean values.

**Comment by mgold1234** [comment]
@regexowl it is looking very clean, amzaing!

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by ezr-ondrej — APPROVED** [review]
I'm good, now for the hard part - convincing CI xD

**Pull request merged**
