### PR TITLE
V2Wizard: Move targets to a constant

### PR DESCRIPTION
**Pull request by regexowl**
This moves mapping between target short and full names to the const to make it reusable.

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
:orange_heart:

**Comment by ezr-ondrej** [comment]
Can't merge, but I'd love to get this in, it's simple change :)

**Comment by regexowl** [comment]
Self merging works :sunglasses: thanks!

**Pull request merged**
