### PR TITLE
Wizard: Validate registration with useValidation

### PR DESCRIPTION
**Pull request by regexowl**
This migrated Registration step validation to `useValidation`.

The scenarios in which the Next button and Create/Save button should be disabled are:
- any of "register now" options is chosen, but no activation key is selected
- activation key is selected, but it's invalid (information about it cannot be fetched)

### CODE REVIEW

**Comment by avitova** [comment]
Nice! I just rebased your solution on my latest local changes for import, and works well. :clap: Thank you, that was very quick!

**Comment by avitova** [comment]
\retest

**Review by mgold1234 — APPROVED** [review]
looks good!

**Pull request merged**
