### PR TITLE
WizardV2: fix google account typo

### PR DESCRIPTION
**Pull request by amirfefer**
This fixes following typo "Google acount" -> "Google account"

### CODE REVIEW

**Comment by regexowl** [comment]
@amirfefer Great catch! Can you please add a short description and re-push so the best-practices check is happy?

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by mgold1234** [comment]
one test is failing FAIL src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js (58.609 s)

**Comment by regexowl** [comment]
> one test is failing FAIL src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js (58.609 s)

The changes are okay. That test is flaking from time to time :melting_face:

**Pull request merged**
