### PR TITLE
test: Cleanup Azure tests

### PR DESCRIPTION
**Pull request by regexowl**
This moves Azure tests from `CreateImageWizard.azure.test.tsx` to `AzureTarget.test.tsx` and cleans up the structure.

### CODE REVIEW

**Review by ezr-ondrej — DISMISSED** [review]
:orange_heart:

**Comment by regexowl** [comment]
There were some async flakes, nothing a few waitFors couldn't fix... hopefully. Let's see.

**Review by ezr-ondrej — APPROVED** [review]
waitFor FTW xD

**Pull request merged**
