### PR TITLE
Wizard: Basic Timezone step (HMS-5009)

### PR DESCRIPTION
**Pull request by regexowl**
This adds bare bones Timezone step with appropriate file structure and basic unit tests.

### CODE REVIEW

**Review by avitova — APPROVED** [review]
As far as I understand, there is supposed to be a placeholder on that step?:)

**Comment by regexowl** [comment]
> As far as I understand, there is supposed to be a placeholder on that step?:)

Exactly, this is just a bare bone step, timezone drop down and ntp server input / drop down will come later.

**Comment by mgold1234** [comment]
hope its ok that I enable the flag for dew second just to see this step locally

**Comment by regexowl** [comment]
> it looks good, I wander if for next step we should see dropdown with different timezone?

Yup, that's the plan!

> hope its ok that I enable the flag for dew second just to see this step locally

Sure! I've kept it disabled, but since this isn't merged yet we can toggle the flag freely.

**Comment by lucasgarfield** [comment]
Can we set the Unleash flag up so it is only exposed in stage-preview, similar to what we're doing for the Users step?

**Comment by regexowl** [comment]
> Can we set the Unleash flag up so it is only exposed in stage-preview, similar to what we're doing for the Users step?

The constraint is there, I kept the flag disabled by default - not sure what the plan is when the changes get released to stage, should the empty, not working step be visible?

Created a disabled flag with the constraint for prod also.

**Comment by lucasgarfield** [comment]
pr_check failing, going to admin merge
`18:11:48 2024-11-19 18:11:48 [   ERROR] [           thread-89] [clowdapp/rhsm-system-profile-bridge] timed out waiting for resource to be ready, details:   clowdapp/rhsm-system-profile-bridge not ready, status conditions:`

**Review by lucasgarfield — APPROVED** [review]
Thanks!

**Pull request merged**
