### PR TITLE
Review and create feedback

### PR DESCRIPTION
**Pull request by Gundersanne**
on error:

https://user-images.githubusercontent.com/11140201/110132872-ee03ed80-7dcb-11eb-9ddf-d2afb5840491.mp4

notification:

https://user-images.githubusercontent.com/11140201/110132891-f1977480-7dcb-11eb-977b-ae21db44002d.mp4

### CODE REVIEW

**Review by teg — APPROVED** [review]
nice :)

**Comment by Gundersanne** [comment]
Don't merge :p

**Comment by katierik** [comment]
Error looks 👍 
Notification toast looks 👍 
The time between clicking "create" and getting feedback is pretty long and with only the disable its still not quite communicative. Can we change the button label as seen [here](https://marvelapp.com/prototype/6g7dja9/screen/76873729)?
image

**Review by jkozol — APPROVED** [review]
LGTM!

**Comment by jkozol** [comment]
@Gundersanne Create button text change looks good to me. The inline conditional is a little confusing but I can't think of a better way...

**Comment by jkozol** [comment]
@Gundersanne I like that change. With validation being added the next button will have a few different states so it will be good to use an if else block.

**Review by jkozol — APPROVED** [review]
Looks good! Thanks for the updates.

**Pull request merged**
