### PR TITLE
jest: Increase test timeout

### PR DESCRIPTION
**Pull request by regexowl**
This increases default test timeout from 10000 to 20000 and timeout for "image name invalid for more than 100 chars and description for 250" to 50000.

This should eliminate test flakes caused by timing out, later it will be "reverted" when the Vitest migration gets merged.

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
I've found many flakes in test Provisioning suite where we have been waitng for some network timeout because of improperly set msw handlers :)
Just saying, lets do this for now for sure, easy solutions are good solutions :sunglasses:

**Review by ezr-ondrej — APPROVED** [review]
Love the branch name! :stuck_out_tongue:

**Comment by regexowl** [comment]
> Just saying, lets do this for now for sure, easy solutions are good solutions 😎

Cool! This should be "reverted" by the vitest migration, but should unblock merging for now

> Love the branch name! 😛

Forgot to update it :sweat_smile:

**Pull request merged**
