### PR TITLE
CI: Drop SonarQube and Schutzbot in favor of Snyk (HMS-3696)

### PR DESCRIPTION
**Pull request by jrusz**
Snyk is now being used for code analysis in favor of Sonarqube. This commit drops Sonarqube. Schutzbot was only neccessary for running SonarQube, so it has also been dropped.

### CODE REVIEW

**Comment by lucasgarfield** [comment]
@jrusz this looks great! Can you add a commit message/PR description that provides a little more context/explanation? We're trying to be a bit more strict about that, you can see we have a new `Verify PR best practices / pr-best-practices (pull_request_target)` action that checks for PR descriptions and a Jira ticket suffix in the PR title (but it is non-blocking now).

So maybe a commit message (and PR description) like this:

"Snyk is now being used for code analysis in favor of Sonarqube. This commit drops Sonarqube. Schutzbot was only neccessary for running SonarQube, so it has also been dropped."

**Comment by jrusz** [comment]
> @jrusz this looks great! Can you add a commit message/PR description that provides a little more context/explanation? We're trying to be a bit more strict about that, you can see we have a new `Verify PR best practices / pr-best-practices (pull_request_target)` action that checks for PR descriptions and a Jira ticket suffix in the PR title (but it is non-blocking now).
> 
> So maybe a commit message (and PR description) like this:
> 
> "Snyk is now being used for code analysis in favor of Sonarqube. This commit drops Sonarqube. Schutzbot was only neccessary for running SonarQube, so it has also been dropped."

I see, it's green so I wouldn't think there's anything wrong, I'll try to add it then... I'll also try to grab some ticket

**Comment by ochosi** [comment]
> > @jrusz this looks great! Can you add a commit message/PR description that provides a little more context/explanation? We're trying to be a bit more strict about that, you can see we have a new `Verify PR best practices / pr-best-practices (pull_request_target)` action that checks for PR descriptions and a Jira ticket suffix in the PR title (but it is non-blocking now).
> > So maybe a commit message (and PR description) like this:
> > "Snyk is now being used for code analysis in favor of Sonarqube. This commit drops Sonarqube. Schutzbot was only neccessary for running SonarQube, so it has also been dropped."
> 
> I see, it's green so I wouldn't think there's anything wrong, I'll try to add it then... I'll also try to grab some ticket

Yup sorry, that was me struggling with mixed return codes in bash. It's red now :innocent:

**Review by ochosi — APPROVED** [review]
LGTM!

**Pull request merged**
