### PR TITLE
templates/testing: Update sel testing image frontend (IQE-2748)

### PR DESCRIPTION
**Pull request by akhil-jha**
We have switched from using a custom selenium image to the upstream variant so updating the testing template accordingly.

### CODE REVIEW

**Comment by akhil-jha** [comment]
@jrusz

**Comment by jrusz** [comment]
@akhil-jha Please add some simple description like a reason why to the commit and MR description. See the failing github workflow for details

**Review by mshriver — APPROVED** [review]
Needs rebase

**Review by jrusz — APPROVED** [review]

**Pull request merged**
