### PR TITLE
Wizard: feature flag to decide environments to be enabled in

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Feature flags now support enablement in Preview specifically.
This allows us to use single feature flag for rollout.

This is set up for `image-builder.firstboot.enabled` in both stage and prod.
Once this is in, we will enable image-builder.firstboot.enabled in stage stable :)

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by regexowl — APPROVED** [review]
Looks good to me! We can review other places we use `isBeta()` and see if we could replace it with a configured flag :broom:

**Pull request merged**
