### PR TITLE
Bump msw

### PR DESCRIPTION
**Pull request by regexowl**
This bumps Mock Service Worker and updates the handlers.

Migrated following https://mswjs.io/docs/migrations/1.x-to-2.x

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I can't find what the new types are called :face_exhaling:
This is what I found: https://mswjs.io/docs/migrations/1.x-to-2.x/#life-cycle-events

**Comment by ezr-ondrej** [comment]
Ah it's just `Request` no funny types: https://github.com/mswjs/msw/blob/bed402cdd9b79ef3084b3195cdcce0d83c7e2cfc/src/core/sharedOptions.ts#L19

**Comment by regexowl** [comment]
Hmm, there seem to be some problems with `Request`, but the bigger issue is that even though I've followed the migration guide I'm not intercepting any requests...

**Comment by ezr-ondrej** [comment]
I'm having bunch of following errors when trying locally
```
An unhandled error occurred processing a request for the endpoint "getBlueprints".
    In the case of an unhandled error, no tags will be "provided" or "invalidated". TypeError: Failed to parse URL from /api/image-builder/v1/blueprints?limit=10&offset=0

at new Request (node_modules/undici/lib/fetch/request.js:84:15)
at node_modules/@reduxjs/toolkit/src/query/fetchBaseQuery.ts:224:21
          ... 3 lines matching cause stack trace ...
          at async Promise.all (index 1) {
        [cause]: TypeError: Invalid URL: /api/image-builder/v1/blueprints?limit=10&offset=0
      at new URLImpl (node_modules/whatwg-url/lib/URL-impl.js:21:13)
      at Object.exports.setup (node_modules/whatwg-url/lib/URL.js:54:12)
      at new URL (node_modules/whatwg-url/lib/URL.js:115:22)
      at new Request (node_modules/undici/lib/fetch/request.js:82:21)
      at node_modules/@reduxjs/toolkit/src/query/fetchBaseQuery.ts:224:21
      at executeEndpoint (node_modules/@reduxjs/toolkit/src/query/core/buildThunks.ts:217:18)
      at node_modules/@reduxjs/toolkit/src/createAsyncThunk.ts:336:27
            at async Promise.all (index 1)
```

**Comment by regexowl** [comment]
Yes, that would be my "not intercepting requests" problem ;_; this PR is not functional, I've marked it as blocked for now as I believe the Vitest migration might help it if I ever manage to make that work

**Comment by ezr-ondrej** [comment]
Is there a chance this now works? :stuck_out_tongue:

**Comment by regexowl** [comment]
> Is there a chance this now works? 😛

I hoped it would, alas it doesn't seem to be as simple :thinking:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
Well I might be biased as part of it is my doing, but I'd say lets get it in :stuck_out_tongue:

**Comment by regexowl** [comment]
Yay! :rocket: Thanks a lot for the help!! :heart:

**Pull request merged**
