### PR TITLE
devDeps: Manually bump msw from 2.4.4 to 2.4.9

### PR DESCRIPTION
**Pull request by regexowl**
This bumps msw from 2.4.4 to 2.4.9

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by regexowl** [comment]
Oh, I've just noticed this one got updated with a merge commit. Let me rebase it without the merge commit. I'll re-request the review in a bit :pray:

**Comment by regexowl** [comment]
Ah, the re-review isn't even needed, nice :) The merge commit should be gone now.

**Pull request merged**
