### PR TITLE
LandingPage: Update 'new' alert for blueprints to support quickstarts

### PR DESCRIPTION
**Pull request by lucasgarfield**
image

### CODE REVIEW

**Comment by kelseamann** [comment]
I don't think we need the | between the two actions, according to our examples here- https://www.patternfly.org/components/alert/

**Comment by lucasgarfield** [comment]
Oh nice, good catch @kelseamann. I found the `|` in old Patternfly documentation example (from version 3 haha). I guess things have changed since then!

**Comment by ezr-ondrej** [comment]
The quickstart is in :)

**Review by ezr-ondrej — APPROVED** [review]
Thanks @lucasgarfield !
I've seen it working.
Inline style in this case is IMO completely fine as the alert will go away eventually.

**Review by regexowl — APPROVED** [review]

**Pull request merged**
