### PR TITLE
test: Add edit mode tests (HMS-4303)

### PR DESCRIPTION
**Pull request by regexowl**
This adds basic edit mode tests for the remaining steps.

### CODE REVIEW

**Comment by regexowl** [comment]
This could be further cleaned up but for now this would assure basic coverage in edit mode for each of the steps of the Wizard.

Expands on https://github.com/osbuild/image-builder-frontend/pull/2033

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — COMMENTED** [review]
Why are you removing the tests for snaphots? :thinking:
(I'm not against it, I just don't understand from first look)

**Comment by regexowl** [comment]
> Why are you removing the tests for snaphots? 🤔 (I'm not against it, I just don't understand from first look)

Do you mean removing the big block with mock fixture? That one was moved to `editMode.ts`. Most of the fixtures are shared between the test file itself and `blueprints.ts` fixtures file so I thought moving all of them to one place from where they can be imported would feel cleaner.

**Review by ezr-ondrej — APPROVED** [review]
Ah! I've missed that file completely! :) IMHO the name is bit missleading, editMode containing all snapshots sound weird, but that's real nitpick.

Great job and nice cleanup! :orange_heart:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by regexowl** [comment]
Yeah, the name might not be the best :sweat_smile: I'm opened to suggestions. The file doesn't contain only mocked snapshots, it includes all mock data we use throughout the edit mode tests (so for packages it contains mock package lists, for oscap it has mock services, mock kernel and so on...). "editMode" was the only thing that came to mind as that's the overarching theme. But maybe we could also call it "blueprintMockData" or something like that? :thinking:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by regexowl** [comment]
Ah right, I didn't want to use "blueprints" in the name originally, because the file is next to the `blueprints.ts` which is a file of blueprints fixtures. I mean the mocked data were partially in `blueprints.ts` and partially scattered between the steps' unit test files so I moved them to one place... naming is hard :melting_face:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
blueprintMockData would be bit better, but I do not have good suggestions :shrug:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
