### PR TITLE
Wizard: validate uniqueness of Blueprint name (HMS-3801)

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Superseedes #1944 to validate blueprint name uniqueness.

Fetches Bluepritnts with the same name as inputed and when there is already one in the database, fails the validation.
This adds a hack in the ValidatedTextInput to accept error to have a special value 'default'

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by regexowl — APPROVED** [review]
Works great, thanks!

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
Why does image building takes so long again? :(

**Comment by regexowl** [comment]
Hmm, this seems to be consistently failing now. :thinking:

@jrusz could you please take a look?

**Comment by jrusz** [comment]
> Hmm, this seems to be consistently failing now. 🤔
> 
> @jrusz could you please take a look?

The image build actually failed, but idk what is the UUID, I need to add a logger line for this.

**Comment by ezr-ondrej** [comment]
The timeoutes are bit annoying :/

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
Cool inventory-frontend would deploy now :face_exhaling:

**Comment by ezr-ondrej** [comment]
/retest

Inventory should be fixed :)

**Comment by ezr-ondrej** [comment]
Now nodejs is having issues xD what the heck is going on... why we have so unstable pipeline xD

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by jrusz** [comment]
> Now nodejs is having issues xD what the heck is going on... why we have so unstable pipeline xD EDIT: also why are we downloading nodejs everytime? Makes you wonder xD

Yeah there is a lot that can go wrong :smile:  ... There is a mechanism that when it fails to downloads nodejs it will build it from source which significantly increases the runtime but it doesn't happen very often.

**Comment by ezr-ondrej** [comment]
> Yeah there is a lot that can go wrong 😄

Yeah I know this is not easy to setup and maintain, that's why people tend to flock self managed pipelines IMO.
Setting up node on GH action is just three lines and it works almost always flawlessly and quickly, just because there is a big team making sure it does.
Unsure how to go about it, but maybe konflux will have what we're looking for? :shrug: It at least have much more teams that would use the shared pipeline pieces :)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
Wow! it went :green_apple: ! Amazing :tada:

**Pull request merged**
