### PR TITLE
V2Wizard: Debounce package search

### PR DESCRIPTION
**Pull request by regexowl**
This debounces package search so it doesn't overwhelm content API with two requests for every character.

### CODE REVIEW

**Review by croissanne — DISMISSED** [review]
Thanks!

**Comment by regexowl** [comment]
Ugh, the timing doesn't play nice with the tests. I'll update those.

**Comment by regexowl** [comment]
All good now :wrench:

**Review by lucasgarfield — APPROVED** [review]
Extremely cool and good!

**Pull request merged**
