### PR TITLE
wizard/registration: Add missing article (typo)

### PR DESCRIPTION
**Pull request by ochosi**
When looking at the registration step I noticed that there was a missing article. So here's a tiny fix!

### CODE REVIEW

**Comment by regexowl** [comment]
Great catch, thank you! Can you please fix the lint error?

**Comment by ezr-ondrej** [comment]
Ah I can't squash on this repo! xD this would be bit better as one commit, but I guess it's not mandatory. It'll be forever known that Simon doesn't know that you always need to run `npm run lint:js -- --fix` because the linter is never happy even if you just add an article xD

**Review by ezr-ondrej — APPROVED** [review]
:orange_heart: attention to detail :)

**Comment by ezr-ondrej** [comment]
:tada:

**Pull request merged**
