### PR TITLE
Wizard: Unify snapshot date format

### PR DESCRIPTION
**Pull request by dominikvagner**
Currently the accepted date format in the UI date-picker is `MM/DD/YYYY`, and the API accepts `YYYY-MM-DD` as the date format.
This PR unifies the date formats (to `YYYY-MM-DD`) and removes unnecessary time conversion functions. 😅 
\
Related Ticket: [🔗HMS-4492](https://issues.redhat.com/browse/HMS-4492)

### CODE REVIEW

**Review by croissanne — APPROVED** [review]

**Review by croissanne — APPROVED** [review]
thank you!

**Comment by regexowl** [comment]
/retest

pr_check reaaaally doesn't want to run automatically on this one :sweat_smile:

**Comment by regexowl** [comment]
pr_check is failing on teardown only which is currently expected. Merging

**Pull request merged**
