### PR TITLE
Wizard: enable nav items properly in Edit mode

### LINKED ISSUE #2220: Details step is disabled on blueprint edit
When editing a blueprint I can't go to the Details step, I have to walk through the wizard to get there which I believe was not the case before. Also the tests are failing on this as when they get to this step the Next button is disabled.

disabled-step

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Fixes #2220

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by regexowl — APPROVED** [review]
Nice one! :sparkles:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
