### PR TITLE
Wizard: Add `isPreview` property to analytics tracking

### PR DESCRIPTION
**Pull request by regexowl**
This adds `isPreview` property to the analytics tracking with the use of chrome's `isBeta()`.

### CODE REVIEW

**Comment by regexowl** [comment]
This needs to wait for the next release of chrome that will address a bug when API didn't propagate changes in the UI env to the scalprum instance. As soon as that's out I'll add the dependency bump to this PR.

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by regexowl** [comment]
pr_check fails on teardown only, merging

**Pull request merged**
