### PR TITLE
test: Remove local mocking of chrome and unleash

### PR DESCRIPTION
**Pull request by avitova**
This is the followup we mentioned [here](https://github.com/osbuild/image-builder-frontend/pull/2292#discussion_r1726471390
). :)

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by avitova** [comment]
Unrelated tests are timing out, let's try again.
/retest

**Review by regexowl — APPROVED** [review]
Thanks for the follow up, looks great! :heart:

**Comment by regexowl** [comment]
Disabling auto-merge for now, we have a pr_check update that will probably need to go in first: https://github.com/osbuild/image-builder-frontend/pull/2427

This PR can go right after that :tada:

**Comment by avitova** [comment]
Thanks, Klara!

**Pull request merged**
