### PR TITLE
api: Update image-builder API

### PR DESCRIPTION
**Pull request by regexowl**
This updates image-builder API by running `npm run api` and addresses problems caused by the update.

### CODE REVIEW

**Comment by regexowl** [comment]
Is using type assertions much of a cop out in this case? :face_with_peeking_eye:

**Comment by ezr-ondrej** [comment]
> Is using type assertions too much of a cop out in this case? 🫣 I mean 'centos-8' should be in the place of distribution in the blueprint but is not in the Distributions type anymore.

Hehe interesting case :stuck_out_tongue: But looks like you've convinced it to work :+1:

**Comment by ezr-ondrej** [comment]
/retest

Not exactly sure what went wrong there xD It looks 100% passed :face_exhaling:

**Review by ezr-ondrej — APPROVED** [review]

**Pull request merged**
