### PR TITLE
Display wizard in modal

### PR DESCRIPTION
**Pull request by jkozol**
The wizard now displays inside a modal. Also the field `isInPage` is removed.

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]
code changes look good, how to you test this locally?

**Review by Gundersanne — APPROVED** [review]

**Comment by Gundersanne** [comment]
@KKoukiou  `npm run test` to run locally, or `npm run travis:verify` for linting as well. `npm run test:single` to make the output slightly more readable since it's not great :p

**Review by Gundersanne — COMMENTED** [review]
Wait why do we want it as a modal?

**Comment by jkozol** [comment]
Marking this as blocked until further discussion about design. @andreasn am I correct in my understanding that the Wizard should be a modal?

**Comment by andreasn** [comment]
> am I correct in my understanding that the Wizard should be a modal?

Yup, that's what Katie recommended, as the rest of the Insights apps use modals for their wizards.

**Comment by jkozol** [comment]
@andreasn thanks for the clarification!

@Gundersanne is it ok if I merge this?

**Comment by andreasn** [comment]
> Wait why do we want it as a modal?

* This is what all other wizards on CRO does.
* Avoids (at least to some extent) the problem where the dropdowns become very, very wide on external monitors.
* Avoids the double left sidebar.
* Makes the application have less modes. Clearer distinction between the image list and the image creation.

**Review by Gundersanne — APPROVED** [review]
Alright, then this is good! Sorry for the confusion.

**Pull request merged**
