### PR TITLE
ESLint: Merge .js and .ts configs to one file (HMS-4309)

### PR DESCRIPTION
**Pull request by regexowl**
Since our code base is now mostly TypeScript, we can merge the configs and have a unified one.

`@typescript-eslint/no-var-requires` was temporarily disabled in webpack configs. These files will be replaced by fec.config.ts in the foreseeable future together with their ESLint override.

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
Nice clean-up :orange_heart: 

I think that the forseeable future is very close, the InsightsBot is quite annoying about it xD

**Comment by regexowl** [comment]
> I think that the forseeable future is very close, the InsightsBot is quite annoying about it xD

Indeed, it's very high on my TO DO list :sweat_smile:

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
