### PR TITLE
Wizard: add warning for the min size in bytes

### PR DESCRIPTION
**Pull request by avitova**
This is a small follow-up to add a warning to our minimum size bug fix. :) Let me know what you think about the message.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Can I see a scrrenshot or get some test data? I still didn't get around to test it :face_exhaling:

**Comment by regexowl** [comment]
> Can I see a scrrenshot or get some test data? I still didn't get around to test it 😮‍💨

image

**Review by regexowl — APPROVED** [review]
The message sounds clear to me :sparkles:  I think this looks really good! Thank you!

**Review by ezr-ondrej — APPROVED** [review]
Thank you @avitova and thanks @regexowl for the help to us, lazy reviewers xD

**Comment by regexowl** [comment]
Hmm, timed out when waiting for the build to start. Let's give it another try

/retest

**Comment by avitova** [comment]
Thanks guys!

**Pull request merged**
