### PR TITLE
devDeps, src: Bump ts-patch and update imports

### PR DESCRIPTION
**Pull request by regexowl**
This bumps ts-patch and updates PF imports where needed.

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
I do not love the specific imports, but sure, if PF insists...
I guess it's for a reason I just don't understand :)

**Comment by regexowl** [comment]
Rebased will need one more review :bow: 

> I do not love the specific imports, but sure, if PF insists...

I think there might be gaps in PF mapper for dynamic files which resolves some imports as `import <nameOfComponent> from 'false';`. This solves the problem on our side by pointing the component to its esm file.

**Review by ezr-ondrej — APPROVED** [review]
I do not understand one bit xD
If it works, I'm good, but might be good to get second pair of eyes given we are setting trend for these imports :shrug:

**Comment by regexowl** [comment]
I think a solution would be to update mapper on PF side. I agree this is not ideal, but if it's okay I'd merge this to address the dep bump. But also created an issue as a reminder to revisit this later: https://github.com/osbuild/image-builder-frontend/issues/2330

**Comment by ezr-ondrej** [comment]
No objections to merge on my side ;)
Just saying I do not understand the impact of esm vs non-esm, the nuances are lost on me, but it builds, so we should be good ;)

**Pull request merged**
