### PR TITLE
Images: add popover when the image is outdated (HMS-3763)

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Add Popover to inform user the image is build for an older then current Blueprint version.

Fixes HMS-3763

image

### CODE REVIEW

**Comment by lucasgarfield** [comment]
Can you lint this @ezr-ondrej? `npm run lint:js:fix` ought to work.

**Comment by ezr-ondrej** [comment]
Oh yeah :face_in_clouds: fixed :+1:

**Comment by ezr-ondrej** [comment]
:green_apple:  :)

**Review by lucasgarfield — APPROVED** [review]
Works nicely! Thank you!

**Pull request merged**
