### PR TITLE
OAuth permissions text shortening

### PR DESCRIPTION
**Pull request by yuxisun1217**
Fix issue #170 

Signed-off-by: Yuxin Sun <yuxisun@redhat.com>

### CODE REVIEW

**Review by atodorov — DISMISSED** [review]
Add `Related: rhbz#1954598` to commit log

**Comment by atodorov** [comment]
> Fix issue #170

Add this to commit log as well so that GitHub will close the issue automatically after the PR is merged.

**Comment by yuxisun1217** [comment]
> > Fix issue #170
> 
> Add this to commit log as well so that GitHub will close the issue automatically after the PR is merged.

Thanks Alex! Have updated commit log. Is this as expected? Thanks!

**Comment by jkozol** [comment]
@yuxisun1217 Thanks for these text changes! In regards to the commit message I generally prefer to use the format of 

```
CreateImageWizard: OAuth permissions text shortening

Fix #170
Related: rhbz#1954598
```

**Review by Gundersanne — APPROVED** [review]
Let's edit the commit message when squashing since it's only 1 commit :) Thank you!

**Comment by yuxisun1217** [comment]
Thanks @jkozol and @Gundersanne ! I'll use this format the next time :)

**Pull request merged**
