### PR TITLE
Vitest migration (HMS-4425)

### PR DESCRIPTION
**Pull request by regexowl**
This migrates our tests from using the Jest testing framework to Vitest: https://vitest.dev/

Use remains mostly the same, the tests can be run with `npm run test`. There is also a new test mode which allows to "watch" the file changes live. Meaning when `npm run test:watch` is run the run goes through the files, but then instead of finishing just pauses. When a new change to the test files is made, the relevant file is automatically rerun.

Three tests were temporarily disabled, the reasons are listed in https://github.com/osbuild/image-builder-frontend/pull/2184/commits/b2667257d56dec4273afb2be2af89ce94399bfe5

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
I've rebased this, IMO we should just get it in :)
We've sacrificed one test, that's a good trade off if it unblocks us :)

**Comment by regexowl** [comment]
Rebased after dependency bumps, also updated the newly added EditImageWizard file to work with vitest. The changes for the update are in a separate commit so it's easier to review :)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]
I didn't review it all, but we've sacrifieced just one test, rest seems to be just adjustments, lets do this, we can improve as we go :)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
:tada: it's in!

**Comment by regexowl** [comment]
> 🎉 it's in!

:tada: yay! Time to check how the MSW bump goes with vitest  :crossed_fingers:

**Pull request merged**
