### PR TITLE
config: Replace webpack configs with FEC config (HMS-4448)

### PR DESCRIPTION
**Pull request by regexowl**
This migrates from previously used webpack configs to one fec.config.js.

This will allow us to bump `frontend-components-config` dependency to version 6.x and stay supported in the future.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
so this might pass now ? :heart_eyes:

**Comment by regexowl** [comment]
> so this might pass now ? 😍

This shouldn't pass yet, but all blockers should now be resolved for the migration to be worked on :wrench:

**Comment by ezr-ondrej** [comment]
Wow! It looks quite :green_apple:ish

**Review by ezr-ondrej — APPROVED** [review]
:tada:

**Comment by regexowl** [comment]
Wow, all green. Do we dare to merge? Carpe diem I guess :upside_down_face: :rocket:

**Comment by ezr-ondrej** [comment]
:shipit: we are done here! :tada:
You've made it, congrats @regexowl ! :)

**Pull request merged**
