### PR TITLE
Wizard: Validate snapshot date with useValidation

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This uses the concept of useValidation for snapshot date.
It is the last validation that doesn't use this.

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I'm drafting this as the custom sub nav item is broken with the error state and the date component is not easy to use the same validation function, but that's kinda the main point, so bit useless without it.

**Comment by ezr-ondrej** [comment]
Well it's not broken, just the text is too long to fit the status :face_exhaling:

image


We could change the text and it works :stuck_out_tongue:
image

Or accept it's "broken" - we do not usually show this to User, as they cannot go next on invalid step, so they need to hack it around :shrug:

**Comment by mgold1234** [comment]
it is look good except one thing, when user go to 'Repository snapshot' step to fix the problem, the error message 'Cannot set a date in the future' doesnt show up

https://github.com/user-attachments/assets/a9ddcdc8-c3a7-4bd4-933d-3b7e0fa0f26d

and I like the changes that the red symbol appear align with the step name

**Comment by regexowl** [comment]
> Or accept it's "broken" - we do not usually show this to User, as they cannot go next on invalid step, so they need to hack it around 🤷

I don't see this as an issue. If the user really wants to mess around then they shouldn't be surprised by an extra line break here and there :smiling_imp:

**Comment by regexowl** [comment]
> it is look good except one thing, when user go to 'Repository snapshot' step to fix the problem, the error message 'Cannot set a date in the future' doesnt show up
> 
> and I like the changes that the red symbol appear align with the step name

Noticed the same issue. I think it's connected to the pristinity of the date picker maybe? If I mess up, go to Review, then jump back to Snapshots the helper error text doesn't show unless I click on the date picker and away again.

snapshot-validation

Otherwise looks great!

**Comment by ezr-ondrej** [comment]
> Noticed the same issue. I think it's connected to the pristinity of the date picker maybe? If I mess up, go to Review, then jump back to Snapshots the helper error text doesn't show unless I click on the date picker and away again.

Hmm the problem is, the pristine is not under our control :/
I've tried to report it as a bug to PF, but in a [codebox](https://codesandbox.io/p/sandbox/optimistic-aryabhata-9rh74r?workspaceId=5569d096-d514-4342-9d7e-3ba70d11da76&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0f4aebm00062v881y81mha5%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0f4aebl00022v88y710l9il%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0f4aebl00032v88qfa412en%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0f4aebl00052v88k2oecqju%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0f4aebl00022v88y710l9il%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0f4aebl00012v8876m78g0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A14%257D%255D%257D%255D%252C%2522id%2522%253A%2522cm0f4aebl00022v88y710l9il%2522%252C%2522activeTabId%2522%253A%2522cm0f4aebl00012v8876m78g0w%2522%257D%252C%2522cm0f4aebl00052v88k2oecqju%2522%253A%257B%2522id%2522%253A%2522cm0f4aebl00052v88k2oecqju%2522%252C%2522activeTabId%2522%253A%2522cm0f4hei200332v87qkl2d1mc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0f4aebl00042v88nav87wwr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0f4hei200332v87qkl2d1mc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0f4aebl00032v88qfa412en%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0f4aebl00032v88qfa412en%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D) it works as expected :(

I'm not sure if I'm able to fix it :thinking:

**Comment by regexowl** [comment]
I see, sorry didn't realize the pristinity is out of our control here :thinking: I'd say in the codebox it works the same way as it does in the PR. When you're manipulating data in the date picker "manually" it doesn't show the helper text unless you click outside of the date picker

helper-text

Which means we're consistent with PatternFly patterns so I'd say all's fine :shrug: And migrating the validation to use `useValidation` is an improvement for sure so let's do this! :rocket: Thanks a lot for looking into it!

**Comment by regexowl** [comment]
Wait, I'm trying to think which is a bit hard today I must admit so please bear with me :sweat_smile: 

Could we use the same style of validation we use in FSC custom footer? Meaning the Next button would stay enabled, but the validation runs upon clicking it and it gets disabled when the validation errors, canceling the pristinity and rendering the helper text?

I'm asking because the same problem applies to https://github.com/osbuild/image-builder-frontend/pull/2374
The Next gets disabled with a duplicate name, but the helper text doesn't render until blur.

I think this could be resolved in a follow up as it's a bit different problem than just migrating snapshot validation to `useValidation`.

**Comment by ezr-ondrej** [comment]
> Could we use the same style of validation we use in FSC custom footer? Meaning the Next button would stay enabled, but the validation runs upon clicking it and it gets disabled when the validation errors, canceling the pristinity and rendering the helper text?

I guess it makes sense :thinking: I don't love what we do there (make you click to see the validation = for me it feels like a bait button), it surfaces the fact of delayed validation more clearly.

**Comment by regexowl** [comment]
I see, also good point :thinking: the thing I'm trying to figure out is which way of validating is better. Either we block the Next button, but don't tell the user why unless they start clicking around the Wizard. Or we allow Next button, but disable it after a click and immediately show errors if there are some.

I'm not sure which method is better. :sweat_smile: I think the second approach is more transparent in the way the error helper texts are handled, but yeah, the enabled Next button which is not really enabled... hmm. Well I still think we can merge this PR and continue discussing the problem in https://github.com/osbuild/image-builder-frontend/pull/2392

**Pull request merged**
