### PR TITLE
test: Silence the DOM dump in test output

### PR DESCRIPTION
**Pull request by regexowl**
This silences the DOM dump logged into test output by testing-library while keeping all the relevant information about the test failure in the output.

New error
```bash
 FAIL  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx > oscap > remove a profile
TestingLibraryElementError: Unable to find role="textbox" and name `/I broke this test on purpose/i`
 ❯ waitForWrapper node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1133:27
    1135| /*
    1136| eslint
    1137|   max-lines-per-function: ["error", {"max": 200}],
       |         ^
    1138| */
    1139| 
 ❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1213:12
 ❯ selectNone src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:85:46
 ❯ src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:153:11
```

Original error
```bash
 FAIL  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx > oscap > remove a profile
TestingLibraryElementError: Unable to find role="textbox" and name `/I broke this test on purpose/i`

Ignored nodes: comments, script, style
<body
  class=""
>
  <div />
  <div>
    <section
      class="pf-v5-l-page-header pf-v5-c-page-header pf-v5-l-page__main-section pf-v5-c-page__main-section pf-m-light"
      data-ouia-component-id="OUIA-Generated-RHI/Header-true-3"
      data-ouia-component-type="RHI/Header"
      data-ouia-safe="true"
      data-testid="image-builder-header"
      widget-type="InsightsPageHeader"
    >
      <div
        class="pf-v5-l-flex"
      >
        <div
          class=""
        >
          <div
            class="pf-v5-l-flex pf-m-justify-content-space-between"
          >
            <div
              class=""
            >
              <h1
                class="pf-v5-c-title pf-m-2xl title"
                data-ouia-component-id="OUIA-Generated-RHI/Header-true-4"
                data-ouia-component-type="RHI/Header"
                data-ouia-safe="true"
                widget-type="InsightsPageHeaderTitle"
              >
                Images 
                <div
                  style="display: contents;"
                >
                  <button
                    aria-disabled="false"
                    aria-label="About image builder"
                    class="pf-v5-c-button pf-m-plain pf-u-pl-sm header-button"
                    data-ouia-component-id="OUIA-Generated-Button-plain-25"
                    data-ouia-component-type="PF5/Button"
                    data-ouia-safe="true"
                    type="button"
                  >
                    <svg
                      aria-hidden="true"
                      class="pf-v5-svg"
                      fill="currentColor"
                      height="1em"
                      role="img"
                      viewBox="0 0 1024 1024"
                      width="1em"
                    >
                      <path
                        d="M521.3,576 C627.5,576 713.7,502 713.7,413.7 C713.7,325.4 627.6,253.6 521.3,253.6 C366,253.6 334.5,337.7 329.2,407.2 C329.2,414.3 335.2,416 343.5,416 L445,416 C450.5,416 458,415.5 460.8,406.5 C460.8,362.6 582.9,357.1 582.9,413.6 C582.9,441.9 556.2,470.9 521.3,473 C486.4,475.1 447.3,479.8 447.3,521.7 L447.3,553.8 C447.3,570.8 456.1,576 472,576 C487.9,576 521.3,576 521.3,576 M575.3,751.3 L575.3,655.3 C575.313862,651.055109 573.620137,646.982962 570.6,644 C567.638831,640.947672 563.552355,639.247987 559.3,639.29884 L463.3,639.29884 C459.055109,639.286138 454.982962,640.979863 452,644 C448.947672,646.961169 447.247987,651.047645 447.29884,655.3 L447.29884,751.3 C447.286138,755.544891 448.979863,759.617038 452,762.6 C454.961169,765.652328 459.047645,767.352013 463.3,767.30116 L559.3,767.30116 C563.544891,767.313862 567.617038,765.620137 570.6,762.6 C573.659349,759.643612 575.360354,755.553963 575.3,751.3 M512,896 C300.2,896 128,723.9 128,512 C128,300.3 300.2,128 512,128 C723.8,128 896,300.2 896,512 C896,723.8 723.7,896 512,896 M512.1,0 C229.7,0 0,229.8 0,512 C0,794.2 229.8,1024 512.1,1024 C794.4,1024 1024,794.3 1024,512 C1024,229.7 794.4,0 512.1,0"
                      />
                    </svg>
                  </button>
                </div>
                <div
                  style="display: contents;"
                >
                  <button
                    aria-disabled="false"
                    aria-label="About Open Services"
                    class="pf-v5-c-button pf-m-plain pf-v5-u-pl-sm open-source-badge"
                    data-ouia-component-id="OUIA-Generated-Button-plain-26"
                    data-ouia-component-type="PF5/Button"
                    data-ouia-safe="true"
                    type="button"
                  >
                    <svg
                      aria-hidden="true"
                      class="pf-v5-svg"
                      fill="currentColor"
                      height="1em"
                      role="img"
                      viewBox="0 0 384 512"
                      width="1em"
                    >
                      <path
                        d="M384 144c0-44.2-35.8-80-80-80s-80 35.8-80 80c0 36.4 24.3 67.1 57.5 76.8-.6 16.1-4.2 28.5-11 36.9-15.4 19.2-49.3 22.4-85.2 25.7-28.2 2.6-57.4 5.4-81.3 16.9v-144c32.5-10.2 56-40.5 56-76.3 0-44.2-35.8-80-80-80S0 35.8 0 80c0 35.8 23.5 66.1 56 76.3v199.3C23.5 365.9 0 396.2 0 432c0 44.2 35.8 80 80 80s80-35.8 80-80c0-34-21.2-63.1-51.2-74.6 3.1-5.2 7.8-9.8 14.9-13.4 16.2-8.2 40.4-10.4 66.1-12.8 42.2-3.9 90-8.4 118.2-43.4 14-17.4 21.1-39.8 21.6-67.9 31.6-10.8 54.4-40.7 54.4-75.9zM80 64c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16zm0 384c-8.8 0-16-7.2-16-16s7.2-16 16-16 16 7.2 16 16-7.2 16-16 16zm224-320c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16z"
                      />
                    </svg>
                  </button>
                </div>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section
      class="pf-l-page__main-section pf-c-page__main-section"
    >
      <div
        class="pf-v5-c-wizard"
      >
        <button
          aria-expanded="false"
          aria-label="Wizard toggle"
          class="pf-v5-c-wizard__toggle"
        >
          <span
            class="pf-v5-c-wizard__toggle-list"
          >
            <span
              class="pf-v5-c-wizard__toggle-list-item"
            >
              <span
         ...

Ignored nodes: comments, script, style
<body
  class=""
>
  <div />
  <div>
    <section
      class="pf-v5-l-page-header pf-v5-c-page-header pf-v5-l-page__main-section pf-v5-c-page__main-section pf-m-light"
      data-ouia-component-id="OUIA-Generated-RHI/Header-true-3"
      data-ouia-component-type="RHI/Header"
      data-ouia-safe="true"
      data-testid="image-builder-header"
      widget-type="InsightsPageHeader"
    >
      <div
        class="pf-v5-l-flex"
      >
        <div
          class=""
        >
          <div
            class="pf-v5-l-flex pf-m-justify-content-space-between"
          >
            <div
              class=""
            >
              <h1
                class="pf-v5-c-title pf-m-2xl title"
                data-ouia-component-id="OUIA-Generated-RHI/Header-true-4"
                data-ouia-component-type="RHI/Header"
                data-ouia-safe="true"
                widget-type="InsightsPageHeaderTitle"
              >
                Images 
                <div
                  style="display: contents;"
                >
                  <button
                    aria-disabled="false"
                    aria-label="About image builder"
                    class="pf-v5-c-button pf-m-plain pf-u-pl-sm header-button"
                    data-ouia-component-id="OUIA-Generated-Button-plain-25"
                    data-ouia-component-type="PF5/Button"
                    data-ouia-safe="true"
                    type="button"
                  >
                    <svg
                      aria-hidden="true"
                      class="pf-v5-svg"
                      fill="currentColor"
                      height="1em"
                      role="img"
                      viewBox="0 0 1024 1024"
                      width="1em"
                    >
                      <path
                        d="M521.3,576 C627.5,576 713.7,502 713.7,413.7 C713.7,325.4 627.6,253.6 521.3,253.6 C366,253.6 334.5,337.7 329.2,407.2 C329.2,414.3 335.2,416 343.5,416 L445,416 C450.5,416 458,415.5 460.8,406.5 C460.8,362.6 582.9,357.1 582.9,413.6 C582.9,441.9 556.2,470.9 521.3,473 C486.4,475.1 447.3,479.8 447.3,521.7 L447.3,553.8 C447.3,570.8 456.1,576 472,576 C487.9,576 521.3,576 521.3,576 M575.3,751.3 L575.3,655.3 C575.313862,651.055109 573.620137,646.982962 570.6,644 C567.638831,640.947672 563.552355,639.247987 559.3,639.29884 L463.3,639.29884 C459.055109,639.286138 454.982962,640.979863 452,644 C448.947672,646.961169 447.247987,651.047645 447.29884,655.3 L447.29884,751.3 C447.286138,755.544891 448.979863,759.617038 452,762.6 C454.961169,765.652328 459.047645,767.352013 463.3,767.30116 L559.3,767.30116 C563.544891,767.313862 567.617038,765.620137 570.6,762.6 C573.659349,759.643612 575.360354,755.553963 575.3,751.3 M512,896 C300.2,896 128,723.9 128,512 C128,300.3 300.2,128 512,128 C723.8,128 896,300.2 896,512 C896,723.8 723.7,896 512,896 M512.1,0 C229.7,0 0,229.8 0,512 C0,794.2 229.8,1024 512.1,1024 C794.4,1024 1024,794.3 1024,512 C1024,229.7 794.4,0 512.1,0"
                      />
                    </svg>
                  </button>
                </div>
                <div
                  style="display: contents;"
                >
                  <button
                    aria-disabled="false"
                    aria-label="About Open Services"
                    class="pf-v5-c-button pf-m-plain pf-v5-u-pl-sm open-source-badge"
                    data-ouia-component-id="OUIA-Generated-Button-plain-26"
                    data-ouia-component-type="PF5/Button"
                    data-ouia-safe="true"
                    type="button"
                  >
                    <svg
                      aria-hidden="true"
                      class="pf-v5-svg"
                      fill="currentColor"
                      height="1em"
                      role="img"
                      viewBox="0 0 384 512"
                      width="1em"
                    >
                      <path
                        d="M384 144c0-44.2-35.8-80-80-80s-80 35.8-80 80c0 36.4 24.3 67.1 57.5 76.8-.6 16.1-4.2 28.5-11 36.9-15.4 19.2-49.3 22.4-85.2 25.7-28.2 2.6-57.4 5.4-81.3 16.9v-144c32.5-10.2 56-40.5 56-76.3 0-44.2-35.8-80-80-80S0 35.8 0 80c0 35.8 23.5 66.1 56 76.3v199.3C23.5 365.9 0 396.2 0 432c0 44.2 35.8 80 80 80s80-35.8 80-80c0-34-21.2-63.1-51.2-74.6 3.1-5.2 7.8-9.8 14.9-13.4 16.2-8.2 40.4-10.4 66.1-12.8 42.2-3.9 90-8.4 118.2-43.4 14-17.4 21.1-39.8 21.6-67.9 31.6-10.8 54.4-40.7 54.4-75.9zM80 64c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16zm0 384c-8.8 0-16-7.2-16-16s7.2-16 16-16 16 7.2 16 16-7.2 16-16 16zm224-320c8.8 0 16 7.2 16 16s-7.2 16-16 16-16-7.2-16-16 7.2-16 16-16z"
                      />
                    </svg>
                  </button>
                </div>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section
      class="pf-l-page__main-section pf-c-page__main-section"
    >
      <div
        class="pf-v5-c-wizard"
      >
        <button
          aria-expanded="false"
          aria-label="Wizard toggle"
          class="pf-v5-c-wizard__toggle"
        >
          <span
            class="pf-v5-c-wizard__toggle-list"
          >
            <span
              class="pf-v5-c-wizard__toggle-list-item"
            >
              <span
         ...
 ❯ waitForWrapper node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1133:27
    1135| /*
    1136| eslint
    1137|   max-lines-per-function: ["error", {"max": 200}],
       |         ^
    1138| */
    1139| 
 ❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1213:12
 ❯ selectNone src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:85:46
 ❯ src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:153:11
```

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by ezr-ondrej** [comment]
Generally I agree it's mostly useless and just makes the output unreadable, but sometimes I'm using `DEBUG_PRINT_LIMIT=70000` to print the full dom, but I guess I can just switch to getting a testing playground link. We can just document that (somewhere in CONTRIBUTING) in a follow-up tho :)

**Review by ezr-ondrej — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
Hmm actually... wouldn't it be easier just to lower the PRINT_LIMIT to 5/10 by default? that way we'd keep the stack, but have more sensible output.

**Comment by ezr-ondrej** [comment]
Feel free to merge tho, I'm just thinking out loud, this works, no need to hold off :+1:

**Comment by regexowl** [comment]
I was thinking of something more global (speaking as someone who doesn't use the DOM dump at all, testing-playground FTW :sweat_smile:), so good point! I'd merge this one for now, if we find out we're missing the DOM dumps we can create a separate script for running the "cleaner" tests or something like that :)

**Comment by ezr-ondrej** [comment]
sure :)

**Pull request merged**
