### PR TITLE
Blueprints: add blueprint's images empty state

### PR DESCRIPTION
**Pull request by amirfefer**
Screenshot 2024-02-21 at 18 38 14

### CODE REVIEW

**Review by avitova — COMMENTED** [review]
Works well, I have a few nitpicks not related to the functionality:)

**Comment by lucasgarfield** [comment]
image

Should the alert appear on the empty state like shown above?

**Review by lucasgarfield — APPROVED** [review]
Thanks @amirfefer. Let's deal with the alert in a follow-up PR.

**Comment by amirfefer** [comment]
Thanks @lucasgarfield ! 
This issue has been fixed here - https://github.com/osbuild/image-builder-frontend/pull/1735

**Pull request merged**
