### PR TITLE
devDeps: Bump msw from 2.3.1 to 2.3.2

### PR DESCRIPTION
**Pull request by regexowl**
This manually bumps msw from 2.3.1 to 2.3.2

### CODE REVIEW

**Comment by regexowl** [comment]
Replaces https://github.com/osbuild/image-builder-frontend/pull/2249

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by ezr-ondrej — APPROVED** [review]

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
