### PR TITLE
Wizard: disable non-snapshot repositories when needed (HMS-4481)

### PR DESCRIPTION
**Pull request by croissanne**
If a snapshot date is selected, all selected repositories need to have snapshotting enabled. So disable the ones which don't have snapshotting enabled.

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by regexowl — APPROVED** [review]
I see so when snapshots are enabled incompatible repositories cannot be selected. Makes sense and looks good, thanks!

I think the PR will need a push to re-trigger the pr-best-practices bot with the updated description.

**Pull request merged**
