### PR TITLE
Wizard: Add Lightspeed to package recommendations (HMS-4340)

### PR DESCRIPTION
**Pull request by regexowl**
This adds "Powered by RHEL Lightspeed" text and popover to the recommended packages expandable.

image

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by mgold1234** [comment]
@regexowl, can you please add jira ticket to that pr?

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by mmenestr** [comment]
LGTM!

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Pull request merged**
