### PR TITLE
pr_check: disable IQE parallel execution

### PR DESCRIPTION
**Pull request by jrusz**
We don't have any tests marked for parallel execution.

### CODE REVIEW

**Review by regexowl — APPROVED** [review]
:sparkles:

**Comment by regexowl** [comment]
What's `replicaset/****-9fffc4c79`? O_o

```
10:07:57 2024-11-28 09:07:57 [   ERROR] [         thread-1500] [replicaset/****-9fffc4c79] timed out waiting for resource to be ready, details:   replicaset/****-9fffc4c79 not ready
```

**Comment by jrusz** [comment]
> What's `replicaset/****-9fffc4c79`? O_o
> 
> ```
> 10:07:57 2024-11-28 09:07:57 [   ERROR] [         thread-1500] [replicaset/****-9fffc4c79] timed out waiting for resource to be ready, details:   replicaset/****-9fffc4c79 not ready
> ```

Hm, if I were to guess, one of the apps/compoments has the same value as some secret so it's masking it in the logs. I'm going to try one more retest and if that fails let's just merge it. I did the same change in the backend and it works as expected https://github.com/osbuild/image-builder/pull/1422

**Comment by jrusz** [comment]
Looking at the pipelines in IQE plugin it's also failing with `rbac-frontend` failing to deploy... Let's just merge this if you're ok with it.

**Comment by regexowl** [comment]
Yup, perfectly fine. Merging.

**Pull request merged**
